job/urls.py
from django.contrib import admin
from django.urls import path
from . import views



app_name="jobs"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addjob/',views.addJob,name = "addjob"),
    path('job/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateJob,name = "update"),
    path('delete/<int:id>',views.deleteJob,name = "delete"),
    path('',views.jobs,name = "jobs"),
    path('comment/<int:id>',views.addComment,name = "comment"),
    
     
]

proje/urls.py
from django.contrib import admin
from django.urls import path,include
from job import views
from django_email_verification import urls as mail_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
urlpatterns = [
     path('admin/', admin.site.urls),
     path('email',include(mail_urls)),
     path('',views.index,name="index"),
     path('about/',views.about,name="about"),
     path('help/',views.help,name="help"),
     path('contact/',views.contact,name="contact"),
     path('contracted/',views.contracted,name="contracted"),
     path('contracted2/',views.contracted2,name="contracted2"),
     path('contractedhelp/',views.contractedhelp,name="contractedhelp"),
     path('user/',include("user.urls")),
     path('mailbody/',include(mail_urls),name="mailbody"),
     path('jobs/',include("job.urls")),
     path('reset_password/',auth_views.PasswordResetView.as_view(),name="reset_password"),
     path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(),name="password_reset_done"),
     path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name="password_reset_confirm"),
     path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(),name="password_reset_complete"),
     
]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import url
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from .views import RegistrationView, UsernameValidationView, EmailValidationView, VerificationView, LoginView

app_name="user"

urlpatterns = [
    path('register', RegistrationView.as_view(), name="register"),
    path('login', LoginView.as_view(), name="login"),
    path('logout/',views.logoutUser,name="logout"),
    
    path('validate-username', csrf_exempt(UsernameValidationView.as_view()),
         name="validate-username"),
    path('validate-email', csrf_exempt(EmailValidationView.as_view()),
         name='validate_email'),
    path('activate/<uidb64>/<token>',
         VerificationView.as_view(), name='activate'),
  
]

templates/includes/navbar.html
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'index'  %}">UNHelp</a>
    
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'about'  %}">Hakkımızda</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'jobs:jobs'  %}">İşler</a>
        </li>
        
      </ul>

      <ul class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'jobs:dashboard'  %}">Kontrol Paneli</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'user:logout'  %}">Çıkış Yap</a>
      </li>
      {% else %}

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'user:login'  %}">Giriş Yap</a>
      </li>
      {% endif %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'user:register'  %}">Kayıt Ol</a>
      </li>
      
      </ul>
    </div>


</nav>