job/urls.py
from django.contrib import admin
from django.urls import path
from . import views



app_name="jobs"

urlpatterns = [
    path('dashboard/',views.dashboard,name = "dashboard"),
    path('addjob/',views.addJob,name = "addjob"),
    path('job/<int:id>',views.detail,name = "detail"),
    path('update/<int:id>',views.updateJob,name = "update"),
    path('delete/<int:id>',views.deleteJob,name = "delete"),
    path('',views.jobs,name = "jobs"),
    path('comment/<int:id>',views.addComment,name = "comment"),
    
     
]

proje/urls.py
from django.contrib import admin
from django.urls import path,include
from job import views
from django_email_verification import urls as mail_urls
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
urlpatterns = [
     path('admin/', admin.site.urls),
     path('email',include(mail_urls)),
     path('',views.index,name="index"),
     path('about/',views.about,name="about"),
     path('help/',views.help,name="help"),
     path('contact/',views.contact,name="contact"),
     path('contracted/',views.contracted,name="contracted"),
     path('contracted2/',views.contracted2,name="contracted2"),
     path('contractedhelp/',views.contractedhelp,name="contractedhelp"),
     path('user/',include("user.urls")),
     path('mailbody/',include(mail_urls),name="mailbody"),
     path('jobs/',include("job.urls")),
     path('reset_password/',auth_views.PasswordResetView.as_view(),name="reset_password"),
     path('reset_password_sent/',auth_views.PasswordResetDoneView.as_view(),name="password_reset_done"),
     path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name="password_reset_confirm"),
     path('reset_password_complete/',auth_views.PasswordResetCompleteView.as_view(),name="password_reset_complete"),
     
]
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.conf.urls import url
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from .views import RegistrationView, UsernameValidationView, EmailValidationView, VerificationView, LoginView

app_name="user"

urlpatterns = [
    path('register', RegistrationView.as_view(), name="register"),
    path('login', LoginView.as_view(), name="login"),
    path('logout/',views.logoutUser,name="logout"),
    
    path('validate-username', csrf_exempt(UsernameValidationView.as_view()),
         name="validate-username"),
    path('validate-email', csrf_exempt(EmailValidationView.as_view()),
         name='validate_email'),
    path('activate/<uidb64>/<token>',
         VerificationView.as_view(), name='activate'),
  
]

job/models.py
from django.db import models
from ckeditor.fields import RichTextField
# Create your models here.
class CaseInsensitiveFieldMixin:

    LOOKUP_CONVERSIONS = {
        'exact': 'iexact',
        'contains': 'icontains',
        'startswith': 'istartswith',
        'endswith': 'iendswith',
        'regex': 'iregex',
        'gt' :'>',
        'gte':'>=',
        'lt':'<',
        'lte':'<=',


            }
    def get_lookup(self, lookup_title):
        converted = self.LOOKUP_CONVERSIONS.get(lookup_title, lookup_title)
        return super().get_lookup(converted)

class CICharField(CaseInsensitiveFieldMixin, models.CharField):
    pass
class CIEmailField(CaseInsensitiveFieldMixin, models.EmailField):
    pass

class Job(models.Model):
    author = models.ForeignKey("auth.User",on_delete=models.CASCADE,default="",verbose_name="İşi Veren Kişi")
    title = CICharField(max_length=50,default="",verbose_name="Başlık")
    district = models.CharField(max_length=20,default="",verbose_name="İlçe")
    location = models.CharField(max_length=50,default="",verbose_name="Konum")
    fee = models.CharField(max_length=50,default="",verbose_name="Ödenecek Ücret")
    email = models.CharField(max_length=50,default="",verbose_name="E-Mail")
    telno = models.CharField(max_length=20,default="",verbose_name="Telefon Numarası")
    content = RichTextField(verbose_name="Bilgiler")
    created_date =models.DateTimeField(auto_now_add=True,verbose_name="Tarih")
    def __str__(self):
        return self.title
    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    job = models.ForeignKey(Job,on_delete=models.CASCADE,verbose_name="İş",related_name="comments")
    comment_author= models.CharField(max_length=50,verbose_name="İsim")
    comment_content = models.CharField(max_length=200,verbose_name="Yorum")
    rate = models.IntegerField(default=0)
    comment_date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    class Meta:
        ordering = ['-comment_date']

job/forms.py
from django import forms
from .models import Job
class JobForm(forms.ModelForm):
    class Meta:
        model= Job
        fields=["title","district","email","telno","location","fee","content"]

job/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import JobForm
from .models import Job,Comment,CaseInsensitiveFieldMixin
from django.db import models
from django.contrib.auth.decorators import login_required #@login_required(login_url ="user:login")

# Create your views here.
def jobs(request):
    keyword= request.GET.get("keyword")

    if keyword:
        jobs = Job.objects.filter(title__contains=keyword)
        return render(request,"jobs.html",{"jobs":jobs})
    jobs = Job.objects.all()

    return render(request,"jobs.html",{"jobs":jobs})
class CICharField(CaseInsensitiveFieldMixin, models.CharField):
    pass
class CIEmailField(CaseInsensitiveFieldMixin, models.EmailField):
    pass

def index(request):
    keyword= request.GET.get("keyword")
    if keyword:
        jobs = Job.objects.filter(title__contains=keyword)
        return render(request,"jobs.html",{"jobs":jobs})
    jobs = Job.objects.all()
    return render(request,"index.html",{"jobs":jobs})

def help(request):
    return render(request,"help.html")
def about(request):
    return render(request,"about.html")
def contact(request):
    return render(request,"contact.html")
def contracted(request):
    return render(request,"contracted.html")
def contracted2(request):
    return render(request,"contracted2.html")
def contractedhelp(request):
    return render(request,"contractedhelp.html")
def mailbody(request):
    return render(request,"mailbody.html")
@login_required(login_url ="user:login")
def dashboard(request):
    jobs = Job.objects.filter(author=request.user)
    context = {

        "jobs":jobs
    }
    return render(request,"dashboard.html",context)



@login_required(login_url ="user:login")
def addJob(request):
    form = JobForm(request.POST or None)
    if form.is_valid():
        job = form.save(commit=False)

        job.author=request.user

        job.save()
        messages.success(request,"İş başarıyla oluşturuldu")
        return redirect("jobs:dashboard")
    return render(request,"addjob.html",{"form":form})



def detail(request,id):
    #job = Job.objects.filter(id=id).first()
    job = get_object_or_404(Job,id=id)
    comments = job.comments.all()
    keyword= request.GET.get("keyword")
    if keyword:
        jobs = Job.objects.filter(title__contains=keyword)
        return render(request,"jobs.html",{"jobs":jobs})
    jobs = Job.objects.all()
    return render(request,"detail.html",{"job":job,"comments":comments,"jobs":jobs})


@login_required(login_url ="user:login")
def updateJob(request,id):
    job = get_object_or_404(Job,id=id)
    form=JobForm(request.POST or None, request.FILES or None,instance=job)
    if form.is_valid():
        job = form.save(commit=False)

        job.author=request.user

        job.save()
        messages.success(request,"İş başarıyla Güncellendi")
        return redirect("jobs:dashboard")


    return render(request,"update.html",{"form":form})
@login_required(login_url ="user:login")
def deleteJob(request,id):
    job = get_object_or_404(Job,id=id)

    job.delete()

    messages.success(request,"İş Başarıyla Silindi")
    return redirect("jobs:dashboard")

def addComment(request,id):
    job=get_object_or_404(Job,id=id)

    if request.method=="POST":
        comment_author = request.POST.get("comment_author")
        comment_content= request.POST.get("comment_content")
        rate= request.POST.get("rate")
        newComment =Comment(comment_author=comment_author,comment_content=comment_content,rate=rate)
        newComment.job=job
        newComment.save()
    return redirect(reverse("jobs:detail",kwargs={"id":id}))

templates/activate_account.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'user:activate' uidb64=uid token=token %}
{% endautoescape %}

templates/login.html
<!doctype html>
{% load static %}
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> Uygulama Girişi</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets\img\logo/faviconfinal.ico' %}">
    {% load static %}
	<!-- CSS here -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
	<link rel="stylesheet" href="{% static 'css\owl.carousel.min.css'%}">
	<link rel="stylesheet" href="{% static 'css\slicknav.css'%}">
    <link rel="stylesheet" href="{% static 'css\flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'css\progressbar_barfiller.css'%}">
    <link rel="stylesheet" href="{% static 'css\gijgo.css'%}">
    <link rel="stylesheet" href="{% static 'css\animate.min.css'%}">
    <link rel="stylesheet" href="{% static 'css\animated-headline.css'%}">
	<link rel="stylesheet" href="{% static 'css\magnific-popup.css'%}">
	<link rel="stylesheet" href="{% static 'css\fontawesome-all.min.css'%}">
	<link rel="stylesheet" href="{% static 'css\themify-icons.css'%}">
	<link rel="stylesheet" href="{% static 'css\slick.css'%}">
	<link rel="stylesheet" href="{% static 'css\nice-select.css'%}">
	<link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>
<body>
    <!-- ? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static 'assets\img\logo/logom.png'%}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start-->


<main class="login-body" data-vide-bg="{% static 'assets/img/login-bg.mp4'%}">
    <!-- Login Admin -->
    <form class="form-default" action="" method="POST">
        {% csrf_token %}
        <div class="login-form">
            <!-- logo-login -->
            <div class="logo-login">
                <a href="{% url 'index' %}"><img src="{% static 'assets\img\logo/faviconfinal.ico'%}" alt=""></a>
            </div>
            <h2>Giriş Yapın</h2>
            <div class="form-input">
                <label for="name">Kullanıcı Adı</label>
                <input
              type="text"
              name="username"
              placeholder="username"
              id="usernameField"
              value="{{fieldValues.username}}"
              class="form-control form-control-sm"
            />
            </div>
            <div class="form-input">
                <label for="name">Şifre</label>
                <input
                type="password"
                name="password"
                placeholder="Password"
                class="form-control form-control-sm"
                id="passwordField"
              />
            </div>
            <div class="form-input pt-30">
                <input type="submit" value="Giriş Yapın">
            </div>
            {% for message in messages %}
                    <p id="messages">{{message}}</p>
                {% endfor %}

            <!-- Forget Password -->
            <a href="{% url 'reset_password' %}" class="forget">Şifrenizi Mi Unuttunuz?</a>
            <!-- Forget Password -->
            <a href="{% url 'user:register' %}" class="registration">Kayıt Ol</a>
            <a href="{% url 'index' %}" class="registration">Anasayfaya Dönmek İçin Tıklayınız</a></div>

        </div>
    </form>
    <!-- /end login form -->
</main>


    <script src="{% static 'js/modernizr-3.5.0.min.js'%}"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="{% static 'js/jquery-1.12.4.min.js'%}"></script>
    <script src="{% static 'js/popper.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <!-- Jquery Mobile Menu -->
    <script src="{% static 'js/jquery.slicknav.min.js'%}"></script>

    <!-- Video bg -->
    <script src="{% static 'js/jquery.vide.js'%}"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="{% static 'js/owl.carousel.min.js'%}"></script>
    <script src="{% static 'js/slick.min.js'%}"></script>
    <!-- One Page, Animated-HeadLin -->
    <script src="{% static 'js/wow.min.js'%}"></script>
    <script src="{% static 'js/animated.headline.js'%}"></script>
    <script src="{% static 'js/jquery.magnific-popup.js'%}"></script>

    <!-- Date Picker -->
    <script src="{% static 'js/gijgo.min.js'%}"></script>
    <!-- Nice-select, sticky -->
    <script src="{% static 'js/jquery.nice-select.min.js'%}"></script>
    <script src="{% static 'js/jquery.sticky.js'%}"></script>
    <!-- Progress -->
    <script src="{% static 'js/jquery.barfiller.js'%}"></script>

    <!-- counter , waypoint,Hover Direction -->
    <script src="{% static 'js/jquery.counterup.min.js'%}"></script>
    <script src="{% static 'js/waypoints.min.js'%}"></script>
    <script src="{% static 'js/jquery.countdown.min.js'%}"></script>
    <script src="{% static 'js/hover-direction-snake.min.js'%}"></script>

    <!-- contact js -->
    <script src="{% static 'js/contact.js'%}"></script>
    <script src="{% static 'js/jquery.form.js'%}"></script>
    <script src="{% static 'js/jquery.validate.min.js'%}"></script>
    <script src="{% static 'js/mail-script.js'%}"></script>
    <script src="{% static 'js/jquery.ajaxchimp.min.js'%}"></script>

    <!-- Jquery Plugins, main Jquery -->
    <script src="{% static 'js/plugins.js'%}"></script>
    <script src="{% static 'js/main.js'%}"></script>

    </body>
</html>

templates/register.html
<!doctype html>
{% load static %}
<html class="no-js" lang="zxx">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title> Uygulama Kayıt</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets\img\logo/faviconfinal.ico' %}">

	<!-- CSS here -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}">
	<link rel="stylesheet" href="{% static 'css/slicknav.css'%}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'css/progressbar_barfiller.css'%}">
    <link rel="stylesheet" href="{% static 'css/gijgo.css'%}">
    <link rel="stylesheet" href="{% static 'css/animate.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/animated-headline.css'%}">
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}">
	<link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css'%}">
	<link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
	<link rel="stylesheet" href="{% static 'css/slick.css'%}">
	<link rel="stylesheet" href="{% static 'css/nice-select.css'%}">
	<link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>
<body>
    <!-- ? Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static 'assets\img/logo/faviconfinal.png'%}" alt="">
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start-->


<!-- Register -->

<main class="login-body" data-vide-bg="{% static 'assets\img/login-bg.mp4'%}">
    <!-- Login Admin -->
    <form class="form-default" action="" method="POST">
        {% csrf_token %}
        <div class="login-form">
            <!-- logo-login -->
            <div class="logo-login">
                <a href="{% url 'index' %}"><img src="{% static 'assets\img/logo/faviconfinal.ico'%}" alt=""></a>
            </div>
            <h2>Kayıt Olun</h2>

            <div class="form-input">
                <label for="name">Kullanıcı Adı</label>
                <input
                type="text"
                name="username"
                placeholder="username"
                id="usernameField"
                value="{{fieldValues.username}}"
                class="form-control form-control-sm"
              />
            </div>
            <div class="form-input">
                <label for="name">Email Adresi</label>
                <input
              type="email"
              name="email"
              placeholder="Email"
              class="form-control form-control-sm"
              id="emailField"

              value="{{fieldValues.email}}"
            />
            </div>
            <div class="form-input">
                <label for="name">Şifre</label>
                <input
              type="password"
              name="password"
              placeholder="Password"
              class="form-control form-control-sm"
              id="passwordField"

            />
            </div>
            <div class="form-input">

                {{form.confirm}}{% for message in messages %}
            <div {% if message.tags %} class="alert alert-sm alert-{{ message.tags }}"{% endif %}>
        {{ message }}
    </div>
    {% endfor %}
            </div>

            <div class="form-input pt-30">
                <input type="submit" name="submit" value="Kayıt Olun">
            </div>

            <!-- Forget Password -->
            <a href="{% url 'user:login' %}" class="registration">Giriş Yapın</a>
            <a href="{% url 'index' %}" class="registration">Anasayfaya Dönmek İçin Tıklayınız</a></div>
        </div>
    </form>
    <!-- /end login form -->
</main>


<script src="{% static 'js/modernizr-3.5.0.min.js'%}"></script>
<!-- Jquery, Popper, Bootstrap -->
<script src="{% static 'js/jquery-1.12.4.min.js'%}"></script>
<script src="{% static 'js/popper.min.js'%}"></script>
<script src="{% static 'js/bootstrap.min.js'%}"></script>
<!-- Jquery Mobile Menu -->
<script src="{% static 'js/jquery.slicknav.min.js'%}"></script>

<!-- Video bg -->
<script src="{% static 'js/jquery.vide.js'%}"></script>

<!-- Jquery Slick , Owl-Carousel Plugins -->
<script src="{% static 'js/owl.carousel.min.js'%}"></script>
<script src="{% static 'js/slick.min.js'%}"></script>
<!-- One Page, Animated-HeadLin -->
<script src="{% static 'js/wow.min.js'%}"></script>
<script src="{% static 'js/animated.headline.js'%}"></script>
<script src="{% static 'js/jquery.magnific-popup.js'%}"></script>

<!-- Date Picker -->
<script src="{% static 'js/gijgo.min.js'%}"></script>
<!-- Nice-select, sticky -->
<script src="{% static 'js/jquery.nice-select.min.js'%}"></script>
<script src="{% static 'js/jquery.sticky.js'%}"></script>
<!-- Progress -->
<script src="{% static 'js/jquery.barfiller.js'%}"></script>

<!-- counter , waypoint,Hover Direction -->
<script src="{% static 'js/jquery.counterup.min.js'%}"></script>
<script src="{% static 'js/waypoints.min.js'%}"></script>
<script src="{% static 'js/jquery.countdown.min.js'%}"></script>
<script src="{% static 'js/hover-direction-snake.min.js'%}"></script>

<!-- contact js -->
<script src="{% static 'js/contact.js'%}"></script>
<script src="{% static 'js/jquery.form.js'%}"></script>
<script src="{% static 'js/jquery.validate.min.js'%}"></script>
<script src="{% static 'js/mail-script.js'%}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js'%}"></script>

<!-- Jquery Plugins, main Jquery -->
<script src="{% static 'js/plugins.js'%}"></script>
<script src="{% static 'js/main.js'%}"></script>

    </body>
</html>